### ISSUE TITLE
nvim-listen.sh: simplyfy NVIM_LISTEN_ADDRESS  definition

### ISSUE THREAD

**Issue by laur89** [carlocab/tmux-nvr#1]
Why invoke `mktemp` twice? `/tmp` will be avail on supported platforms, so why not just do `NVIM_LISTEN_ADDRESS "$(mktemp -u "/tmp/XXXXXX")"`

**Comment by carlocab** [comment]
Hi @laur89,

`mktemp` on macOS will not use `/tmp`, but instead points to `$TMPDIR` (which itself is something like `/var/folders/kb/longrandomstring/T/`).

Using `mktemp` twice appears to be the best way to ensure portability, as shown in the accepted answer here: https://unix.stackexchange.com/questions/174817/finding-the-correct-tmp-dir-on-multiple-platforms

I'm happy to simplify the code there. I actually don't expect problems with just using `/tmp`, but I figured it's safer to let the system tell me what the temporary directory is just in case.

**Comment by laur89** [comment]
Sry, wasn't aware of the Mac angle!

**Comment by carlocab** [comment]
No problem! I'm pleased you had a look at the code, and don't mind entertaining questions about it. It's one way to spot mistakes I might've made, after all.
