### ISSUE TITLE
set-hook -> set-option?

### ISSUE THREAD

**Issue by laur89** [carlocab/tmux-nvr#2]
I don't fully grasp the issue, but there seems to be some corner-case with hooks here: https://github.com/carlocab/tmux-nvr/blob/main/nvr.tmux#L18

[tmux v2 change notes](https://raw.githubusercontent.com/tmux/tmux/3.0a/CHANGES) suggests `set-hook` can be replaced w/ `set-option` that already allows multiple values:

    * Hooks are now stored in the options tree as array options, allowing them to
    have multiple separate commands. set-hook and show-hooks remain but
    set-option and show-options can now also be used (show-options will only show
    hooks if given the -H flag). Hooks with multiple commands are run in index
    order.

**Comment by carlocab** [comment]
I'm not sure what corner case you're referring to. Could you elaborate on that?

`set-hook` and `set-option` are equivalent for hooks, as explained [here](http://man.openbsd.org/OpenBSD-current/man1/tmux.1#HOOKS). I prefer `set-hook` because the intent of the command is more transparent. They both need an index to be specified to define multiple hooks.

**Comment by laur89** [comment]
I'm referring to this:

    It should just work, unless you have existing session-created tmux hooks.
    If this applies, you need to specify an unused index in the session-created array using the @tmux-nvr-hook-index option in tmux.conf. For example,

**Comment by carlocab** [comment]
Yes. Replacing `set-hook` with `set-option` will not change that part of the README. You will still need to specify indices of the `session-created` hook array even when setting it via `set-option`, as stated in the section in the manual on hooks.

**Comment by laur89** [comment]
Oh well.

**Comment by carlocab** [comment]
Yup, I don't like having to choose indices for hooks either. I guess it's part of having written tmux in C.

Thanks for trying to think of a fix though!

**Comment by carlocab** [comment]
By the way, I've fixed this now. Thanks for pushing me to look into it.

**Comment by laur89** [comment]
Glad to hear!
Is it this? https://github.com/carlocab/tmux-nvr/commit/1f252ce4ea67ee4c9916eb2734d1a7d9ab04ea8a

**Comment by carlocab** [comment]
Yes, that one.
