### ISSUE TITLE
Use tmux functionality to pass variable into the shell environment

### ISSUE THREAD

**Issue by jceb** [carlocab/tmux-nvr#3]
The following command transfers the variable into the environment of the shell. Saves a few lines.

```
set-option -ga update-environment 'NVIM_LISTEN_ADDRESS'
```

**Comment by carlocab** [comment]
Thanks.

There's a bit of an issue about when `tmux` decides to do `update-environment`. I actually asked about this here: https://github.com/tmux/tmux/issues/2455

Do you mind opening a PR so I can get a clearer understanding of what you have in mind?

**Comment by carlocab** [comment]
Resolved in #4.
